import Navbar from '@/Components/Navbar/Page'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Footer/Footer'
import HeaderBanner from '@/Components/HeaderBanner/HeaderBanner'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const navMenu= ["Home", "About", "Services", "Contact"]
  const navMenu=[{"name":"প্রচ্ছদ", "link":"/"}, {"name":"জামিয়া পরিচিতি", "link":"/about"}, {"name":"ফি প্রদান", "link":"/payment"}, {"name":"যোগাযোগ", "link":"/contact"},
  // {"name":"লগ ইন", "link":"/login"}
]
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <HeaderBanner/>
      <Navbar navMenu={navMenu}/>
      <div>{children}</div>
      <Footer/>
      </body>
    </html>
  )
}
